[package]
name = "js_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
js_lexer = { path = "js_lexer" }
lr1_rs = { path = "lr1_rs" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
