[package]
name = "lr1_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toy_lang_lexer = { path = "./lex" }

[[bin]]
name = "t1"
path = "src/bin/t1.rs"
